export const LOAD_ARTISTS_SUCCESS = 'LOAD_ARTISTS_SUCCESS';

export const QUERY_PLAYLIST_SUCCESS = 'QUERY_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_NEXT_SUCCESS = 'ADD_PLAYLIST_NEXT_SUCCESS';
export const PUSH_PLAYLIST_SUCCESS = 'PUSH_PLAYLIST_SUCCESS';
export const REMOVE_PLAYLIST_SUCCESS = 'REMOVE_PLAYLIST_SUCCESS';
export const CLEAR_PLAYLIST_SUCCESS = 'CLEAR_PLAYLIST_SUCCESS';
export const SHUFFLE_PLAYLIST_SUCCESS = 'SHUFFLE_PLAYLIST_SUCCESS';

export const QUERY_SONGHIST_SUCCESS = 'QUERY_SONGHIST_SUCCESS';
export const PUSH_SONGHIST_SUCCESS = 'PUSH_SONGHIST_SUCCESS';
export const CLEAR_SONGHIST_SUCCESS = 'CLEAR_SONGHIST_SUCCESS';
